defaults:
  - dataset: swat
  - model: patchtrad
  - dataset_model: ${model}/${dataset}

  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

  
hydra:  
  output_subdir: null  
  run:  
    dir: .