name: smap

bs: 128
ws: 99
in_dim: 25

lr: 0.0001
epochs: 10
pct_start: 0.3
Mlr: 0.00001
affine: true
subtract_last: false
patch_size: 8
patch_stride: 6
cf_dim: 64
e_layers: 3
n_heads: 8
d_ff: 128
d_model: 128
head_dim: 32
individual: 1
dropout: 0.1
head_dropout: 0.8
inference_patch_stride: 1
inference_patch_size: 32
temperature: 0.1
dc_lambda: 0.005
auxi_lambda: 0.005
score_lambda: 0.05
regular_lambda: 0.5